packages:
  # all packages in direct subdirs of packages/
  - "packages/front"
  - "packages/server"
  - "packages/sdk/*"
  # all packages in subdirs of components/
  - "components/**"
  # exclude packages that are inside test directories
  - "!**/test/**"
